### PR TITLE
made a mobile splash page

### PR DESCRIPTION
**Pull request by intersim**
@paloobi @mbogor hey guys, I made a mobile splash page that says "Thank you for visiting! Unfortunately, Symph is not available for mobile devices. Please visit us again on a desktop computer!"... it should be up on symph-staging.herokuapp.com soon, I'll merge it in a couple days if there are no objections.

### CODE REVIEW

**Comment by intersim** [comment]
Here are some screenshots: 

iPhone6, Portrait
screen shot 2016-06-29 at 11 18 03 pm

and iPhone6, Landscape
screen shot 2016-06-29 at 11 17 48 pm

**Comment by paloobi** [comment]
Thank you thank you!! Great idea!
Is there a reason you chose to use min-device-width & max-device-width instead of min-width and max-width?

**Comment by paloobi** [comment]
(since it's device-width, I can't check if this works on my computer)

**Comment by paloobi** [comment]
Can confirm this works on my Android device

**Pull request merged**
